### ISSUE TITLE
Use <nav> tag instead of role="navigation"

### ISSUE THREAD

**Issue by amagnolo** [vaadin/vcf-nav#7]
According to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role
> It is preferable to use the HTML5 \<nav\> element to define a navigation landmark. [...] Developers should always prefer using the correct semantic HTML element over using ARIA.

So the implementation of vcf-nav should use the \<nav\> tag instead of role="navigation".

**Comment by jouni** [comment]
Thanks for the feedback. 

I think we don't need to do that here. I would rather avoid adding the extra element, if an attribute gives us the same result, when we’re creating a new custom element. This is pending testing with various OS and screen reader combos. I tested it with macOS + VoiceOver, works the same as using a native `<nav>` element.

If I was authoring a webpage/template (vs a reusable web component), I would definitely use `<nav>` instead of, for example, `<div role="navigation">`. But in the case of `<vcf-nav>`, we can't change the host element to be a native `<nav>` element, so the role is used.
